-- Users Default Insertions --

INSERT INTO USERS (ID, EMAIL_ID, FIRST_NAME, LAST_NAME, PHONE_NO) VALUES 
(1113, 'dummy@gmail.com', 'Dummy', 'User', 7777777777);


-- Slot Default Insertions --

INSERT INTO SLOT_ID (SLOT_ID, _FROM, _TO, DATE) VALUES
(998, '10:00', '12:00', CURDATE()+2),
(999, '1:30', '3:30', CURDATE()+2);


-- AppointmentDetails Default Insertions --

INSERT INTO APPOINTMENT_DETAILS (ID, MONTH_ID, MONTH_NAME, SLOT_ID) VALUES 
(888, MONTH(CURDATE()+2), MONTH(CURDATE()+2), SELECT SLOT_ID FROM SLOT_ID WHERE SLOT_ID = 998),
(889, MONTH(CURDATE()+2), MONTH(CURDATE()+2), SELECT SLOT_ID FROM SLOT_ID WHERE SLOT_ID = 999);

-- Setting User Appointment Details

UPDATE USERS SET APPOINTMENT_ID = SELECT ID FROM APPOINTMENT_DETAILS WHERE ID = 889;